---
name: ci

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run Chef Delivery
        uses: actionshub/chef-delivery@master
        env:
          CHEF_LICENSE: accept-no-persist

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run yaml Lint
        uses: actionshub/yamllint@master

  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@master

  dokken:
    needs: [mdl, yamllint, delivery]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - 'ubuntu-1604'
          - 'ubuntu-1804'
        suite:
          - 'installation-script-main'
          - 'installation-script-test'
          # Upstream issue: Could not resolve host: apt.dockerproject.org
          # - 'installation-script-experimental'
          - 'installation-package'
          - 'installation-tarball'
          # TODO(ramereth): Does not work properly with dokken and should be
          # tested manually with kitchen-vagrant.
          # - 'resources'
          - 'network'
          - 'volume'
          - 'registry'
          - 'smoke'
        include:
          - os: debian-9
            suite: installation-package
          - os: debian-10
            suite: installation-package
          - os: centos-7
            suite: installation-package
          - os: fedora-latest
            suite: installation-package
          - os: debian-9
            suite: resources
          - os: debian-10
            suite: resources
          - os: centos-7
            suite: resources
          - os: fedora-latest
            suite: resources
        exclude:
          - os: ubuntu-1604
            suite: network
          - os: ubuntu-1604
            suite: volume
          - os: ubuntu-1604
            suite: registry
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Install Chef
        uses: actionshub/chef-install@master
      - name: Dokken
        uses: actionshub/kitchen-dokken@master
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
      - name: Print debug output on failure
        if: failure()
        run: |
            set -x
            sudo journalctl -l --since today
            KITCHEN_LOCAL_YAML=kitchen.dokken.yml /usr/bin/kitchen exec ${{ matrix.suite }}-${{ matrix.os }} -c "journalctl -l"

  final:
    needs: [dokken]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
